#!/usr/bin/env bash

set -e

echo -e "\n-----PRE-COMMIT start -----"
echo -e "Start lint code quality with biome"
bun run lint.check
echo -e "Check biome format successfully."
# echo "Start to check typings in projects"
# bun run lint:duplicate
# echo "Start to check typings in projects"
echo -e "-----PRE-COMMIT end -----\n"
