#!/usr/bin/env bash

set -e

branchName=$(git rev-parse --abbrev-ref HEAD)
ivtTicketRegex='^[A-Z0-9]{2,8}-[0-9]{1,5}|merge|hotfix|release'

gitCommitMsg=$(head -n 1 "$1") # $1 is path = .git/COMMIT_EDITMSG

echo -e "-----PREPARE-COMMIT-MSG start -----\n"
if [[ $gitCommitMsg =~ $ivtTicketRegex ]];then
  echo -e "Already exist prefix branch-name, ignore appending prefix."
else
  echo -e "Starting append prefix branch-name..."
  if [[ -n "$branchName" ]] && [[ $branchName =~ $ivtTicketRegex ]]; then
    # Append prefix branch name into commit message
    sed -i.bak "1s~^~$branchName ~" "$1"
    echo -e "Append prefix branch-name successfully."
  fi
fi

echo "-----PREPARE-COMMIT-MSG end -----\n"
