#!/usr/bin/env powershell
$ErrorActionPreference = 'Stop'
$PSNativeCommandErrorActionPreference = $true

# Automatically generated by moon. DO NOT MODIFY!
# https://moonrepo.dev/docs/guides/vcs-hooks

.moon/githooks/post-checkout

if ($LASTEXITCODE -ne 0) {
  exit $LASTEXITCODE
}
